/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApiApprovalsRouteImport } from './routes/api.approvals'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiJobsRouteImport } from './routes/api.jobs'
import { Route as ApiKnowledgeRouteImport } from './routes/api.knowledge'
import { Route as ApiMissionsRouteImport } from './routes/api.missions'
import { Route as ApiObservabilityRouteImport } from './routes/api.observability'
import { Route as ApiSecurityAuditRouteImport } from './routes/api.security-audit'
import { Route as ApiSecurityLessonsRouteImport } from './routes/api.security-lessons'
import { Route as ApiStatusRouteImport } from './routes/api.status'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiKnowledgeFileRouteImport } from './routes/api.knowledge.file'
import { Route as ApiKnowledgeProcessRouteImport } from './routes/api.knowledge.process'
import { Route as ApiKnowledgeSearchRouteImport } from './routes/api.knowledge.search'
import { Route as ApiMissionsStreamRouteImport } from './routes/api.missions.stream'
import { Route as ApiToolsExecuteRouteImport } from './routes/api.tools.execute'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApprovalsRoute = ApiApprovalsRouteImport.update({
  id: '/api/approvals',
  path: '/api/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeRoute = ApiKnowledgeRouteImport.update({
  id: '/api/knowledge',
  path: '/api/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMissionsRoute = ApiMissionsRouteImport.update({
  id: '/api/missions',
  path: '/api/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObservabilityRoute = ApiObservabilityRouteImport.update({
  id: '/api/observability',
  path: '/api/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSecurityAuditRoute = ApiSecurityAuditRouteImport.update({
  id: '/api/security-audit',
  path: '/api/security-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSecurityLessonsRoute = ApiSecurityLessonsRouteImport.update({
  id: '/api/security-lessons',
  path: '/api/security-lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeFileRoute = ApiKnowledgeFileRouteImport.update({
  id: '/file',
  path: '/file',
  getParentRoute: () => ApiKnowledgeRoute,
} as any)
const ApiKnowledgeProcessRoute = ApiKnowledgeProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => ApiKnowledgeRoute,
} as any)
const ApiKnowledgeSearchRoute = ApiKnowledgeSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiKnowledgeRoute,
} as any)
const ApiMissionsStreamRoute = ApiMissionsStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiMissionsRoute,
} as any)
const ApiToolsExecuteRoute = ApiToolsExecuteRouteImport.update({
  id: '/api/tools/execute',
  path: '/api/tools/execute',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/approvals': typeof ApiApprovalsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/knowledge': typeof ApiKnowledgeRouteWithChildren
  '/api/missions': typeof ApiMissionsRouteWithChildren
  '/api/observability': typeof ApiObservabilityRoute
  '/api/security-audit': typeof ApiSecurityAuditRoute
  '/api/security-lessons': typeof ApiSecurityLessonsRoute
  '/api/status': typeof ApiStatusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/knowledge/file': typeof ApiKnowledgeFileRoute
  '/api/knowledge/process': typeof ApiKnowledgeProcessRoute
  '/api/knowledge/search': typeof ApiKnowledgeSearchRoute
  '/api/missions/stream': typeof ApiMissionsStreamRoute
  '/api/tools/execute': typeof ApiToolsExecuteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/approvals': typeof ApiApprovalsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/knowledge': typeof ApiKnowledgeRouteWithChildren
  '/api/missions': typeof ApiMissionsRouteWithChildren
  '/api/observability': typeof ApiObservabilityRoute
  '/api/security-audit': typeof ApiSecurityAuditRoute
  '/api/security-lessons': typeof ApiSecurityLessonsRoute
  '/api/status': typeof ApiStatusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/knowledge/file': typeof ApiKnowledgeFileRoute
  '/api/knowledge/process': typeof ApiKnowledgeProcessRoute
  '/api/knowledge/search': typeof ApiKnowledgeSearchRoute
  '/api/missions/stream': typeof ApiMissionsStreamRoute
  '/api/tools/execute': typeof ApiToolsExecuteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/approvals': typeof ApiApprovalsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/knowledge': typeof ApiKnowledgeRouteWithChildren
  '/api/missions': typeof ApiMissionsRouteWithChildren
  '/api/observability': typeof ApiObservabilityRoute
  '/api/security-audit': typeof ApiSecurityAuditRoute
  '/api/security-lessons': typeof ApiSecurityLessonsRoute
  '/api/status': typeof ApiStatusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/knowledge/file': typeof ApiKnowledgeFileRoute
  '/api/knowledge/process': typeof ApiKnowledgeProcessRoute
  '/api/knowledge/search': typeof ApiKnowledgeSearchRoute
  '/api/missions/stream': typeof ApiMissionsStreamRoute
  '/api/tools/execute': typeof ApiToolsExecuteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/approvals'
    | '/api/chat'
    | '/api/health'
    | '/api/jobs'
    | '/api/knowledge'
    | '/api/missions'
    | '/api/observability'
    | '/api/security-audit'
    | '/api/security-lessons'
    | '/api/status'
    | '/api/auth/$'
    | '/api/knowledge/file'
    | '/api/knowledge/process'
    | '/api/knowledge/search'
    | '/api/missions/stream'
    | '/api/tools/execute'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/api/approvals'
    | '/api/chat'
    | '/api/health'
    | '/api/jobs'
    | '/api/knowledge'
    | '/api/missions'
    | '/api/observability'
    | '/api/security-audit'
    | '/api/security-lessons'
    | '/api/status'
    | '/api/auth/$'
    | '/api/knowledge/file'
    | '/api/knowledge/process'
    | '/api/knowledge/search'
    | '/api/missions/stream'
    | '/api/tools/execute'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/approvals'
    | '/api/chat'
    | '/api/health'
    | '/api/jobs'
    | '/api/knowledge'
    | '/api/missions'
    | '/api/observability'
    | '/api/security-audit'
    | '/api/security-lessons'
    | '/api/status'
    | '/api/auth/$'
    | '/api/knowledge/file'
    | '/api/knowledge/process'
    | '/api/knowledge/search'
    | '/api/missions/stream'
    | '/api/tools/execute'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ApiApprovalsRoute: typeof ApiApprovalsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiJobsRoute: typeof ApiJobsRoute
  ApiKnowledgeRoute: typeof ApiKnowledgeRouteWithChildren
  ApiMissionsRoute: typeof ApiMissionsRouteWithChildren
  ApiObservabilityRoute: typeof ApiObservabilityRoute
  ApiSecurityAuditRoute: typeof ApiSecurityAuditRoute
  ApiSecurityLessonsRoute: typeof ApiSecurityLessonsRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiToolsExecuteRoute: typeof ApiToolsExecuteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/approvals': {
      id: '/api/approvals'
      path: '/api/approvals'
      fullPath: '/api/approvals'
      preLoaderRoute: typeof ApiApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge': {
      id: '/api/knowledge'
      path: '/api/knowledge'
      fullPath: '/api/knowledge'
      preLoaderRoute: typeof ApiKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/missions': {
      id: '/api/missions'
      path: '/api/missions'
      fullPath: '/api/missions'
      preLoaderRoute: typeof ApiMissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observability': {
      id: '/api/observability'
      path: '/api/observability'
      fullPath: '/api/observability'
      preLoaderRoute: typeof ApiObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/security-audit': {
      id: '/api/security-audit'
      path: '/api/security-audit'
      fullPath: '/api/security-audit'
      preLoaderRoute: typeof ApiSecurityAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/security-lessons': {
      id: '/api/security-lessons'
      path: '/api/security-lessons'
      fullPath: '/api/security-lessons'
      preLoaderRoute: typeof ApiSecurityLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/file': {
      id: '/api/knowledge/file'
      path: '/file'
      fullPath: '/api/knowledge/file'
      preLoaderRoute: typeof ApiKnowledgeFileRouteImport
      parentRoute: typeof ApiKnowledgeRoute
    }
    '/api/knowledge/process': {
      id: '/api/knowledge/process'
      path: '/process'
      fullPath: '/api/knowledge/process'
      preLoaderRoute: typeof ApiKnowledgeProcessRouteImport
      parentRoute: typeof ApiKnowledgeRoute
    }
    '/api/knowledge/search': {
      id: '/api/knowledge/search'
      path: '/search'
      fullPath: '/api/knowledge/search'
      preLoaderRoute: typeof ApiKnowledgeSearchRouteImport
      parentRoute: typeof ApiKnowledgeRoute
    }
    '/api/missions/stream': {
      id: '/api/missions/stream'
      path: '/stream'
      fullPath: '/api/missions/stream'
      preLoaderRoute: typeof ApiMissionsStreamRouteImport
      parentRoute: typeof ApiMissionsRoute
    }
    '/api/tools/execute': {
      id: '/api/tools/execute'
      path: '/api/tools/execute'
      fullPath: '/api/tools/execute'
      preLoaderRoute: typeof ApiToolsExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiKnowledgeRouteChildren {
  ApiKnowledgeFileRoute: typeof ApiKnowledgeFileRoute
  ApiKnowledgeProcessRoute: typeof ApiKnowledgeProcessRoute
  ApiKnowledgeSearchRoute: typeof ApiKnowledgeSearchRoute
}

const ApiKnowledgeRouteChildren: ApiKnowledgeRouteChildren = {
  ApiKnowledgeFileRoute: ApiKnowledgeFileRoute,
  ApiKnowledgeProcessRoute: ApiKnowledgeProcessRoute,
  ApiKnowledgeSearchRoute: ApiKnowledgeSearchRoute,
}

const ApiKnowledgeRouteWithChildren = ApiKnowledgeRoute._addFileChildren(
  ApiKnowledgeRouteChildren,
)

interface ApiMissionsRouteChildren {
  ApiMissionsStreamRoute: typeof ApiMissionsStreamRoute
}

const ApiMissionsRouteChildren: ApiMissionsRouteChildren = {
  ApiMissionsStreamRoute: ApiMissionsStreamRoute,
}

const ApiMissionsRouteWithChildren = ApiMissionsRoute._addFileChildren(
  ApiMissionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ApiApprovalsRoute: ApiApprovalsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiJobsRoute: ApiJobsRoute,
  ApiKnowledgeRoute: ApiKnowledgeRouteWithChildren,
  ApiMissionsRoute: ApiMissionsRouteWithChildren,
  ApiObservabilityRoute: ApiObservabilityRoute,
  ApiSecurityAuditRoute: ApiSecurityAuditRoute,
  ApiSecurityLessonsRoute: ApiSecurityLessonsRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiToolsExecuteRoute: ApiToolsExecuteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
