/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApiApprovalsRouteImport } from './routes/api.approvals'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiJobsRouteImport } from './routes/api.jobs'
import { Route as ApiMissionsRouteImport } from './routes/api.missions'
import { Route as ApiObservabilityRouteImport } from './routes/api.observability'
import { Route as ApiStatusRouteImport } from './routes/api.status'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiToolsExecuteRouteImport } from './routes/api.tools.execute'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApprovalsRoute = ApiApprovalsRouteImport.update({
  id: '/api/approvals',
  path: '/api/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMissionsRoute = ApiMissionsRouteImport.update({
  id: '/api/missions',
  path: '/api/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObservabilityRoute = ApiObservabilityRouteImport.update({
  id: '/api/observability',
  path: '/api/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsExecuteRoute = ApiToolsExecuteRouteImport.update({
  id: '/api/tools/execute',
  path: '/api/tools/execute',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/approvals': typeof ApiApprovalsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/missions': typeof ApiMissionsRoute
  '/api/observability': typeof ApiObservabilityRoute
  '/api/status': typeof ApiStatusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tools/execute': typeof ApiToolsExecuteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/approvals': typeof ApiApprovalsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/missions': typeof ApiMissionsRoute
  '/api/observability': typeof ApiObservabilityRoute
  '/api/status': typeof ApiStatusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tools/execute': typeof ApiToolsExecuteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/approvals': typeof ApiApprovalsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/missions': typeof ApiMissionsRoute
  '/api/observability': typeof ApiObservabilityRoute
  '/api/status': typeof ApiStatusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tools/execute': typeof ApiToolsExecuteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/approvals'
    | '/api/chat'
    | '/api/jobs'
    | '/api/missions'
    | '/api/observability'
    | '/api/status'
    | '/api/auth/$'
    | '/api/tools/execute'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/api/approvals'
    | '/api/chat'
    | '/api/jobs'
    | '/api/missions'
    | '/api/observability'
    | '/api/status'
    | '/api/auth/$'
    | '/api/tools/execute'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/approvals'
    | '/api/chat'
    | '/api/jobs'
    | '/api/missions'
    | '/api/observability'
    | '/api/status'
    | '/api/auth/$'
    | '/api/tools/execute'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ApiApprovalsRoute: typeof ApiApprovalsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiJobsRoute: typeof ApiJobsRoute
  ApiMissionsRoute: typeof ApiMissionsRoute
  ApiObservabilityRoute: typeof ApiObservabilityRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiToolsExecuteRoute: typeof ApiToolsExecuteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/approvals': {
      id: '/api/approvals'
      path: '/api/approvals'
      fullPath: '/api/approvals'
      preLoaderRoute: typeof ApiApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/missions': {
      id: '/api/missions'
      path: '/api/missions'
      fullPath: '/api/missions'
      preLoaderRoute: typeof ApiMissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observability': {
      id: '/api/observability'
      path: '/api/observability'
      fullPath: '/api/observability'
      preLoaderRoute: typeof ApiObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools/execute': {
      id: '/api/tools/execute'
      path: '/api/tools/execute'
      fullPath: '/api/tools/execute'
      preLoaderRoute: typeof ApiToolsExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ApiApprovalsRoute: ApiApprovalsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiJobsRoute: ApiJobsRoute,
  ApiMissionsRoute: ApiMissionsRoute,
  ApiObservabilityRoute: ApiObservabilityRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiToolsExecuteRoute: ApiToolsExecuteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
